# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/projects_test',
                'doc_host': 'https://LeeWilli.github.io',
                'git_url': 'https://github.com/LeeWilli/projects_test',
                'lib_path': 'projects_test'},
  'syms': {'projects_test.core': {}}}
