# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/projects_test',
                'doc_host': 'https://LeeWilli.github.io',
                'git_url': 'https://github.com/LeeWilli/projects_test',
                'lib_path': 'projects_test'},
  'syms': { 'projects_test.core': { 'projects_test.core.detect_pulse': ('heart.html#detect_pulse', 'projects_test/core.py'),
                                    'projects_test.core.send_frame': ('heart.html#send_frame', 'projects_test/core.py')}}}
